version: "3"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "5000:5000"
    env_file:
      - .env
    volumes:
      - /usr/src/app/node_modules
      - ./:/usr/src/app
